##############################
#	fl_cust
##############################
op.create_table(
    'fl_cust',
    sa.Column('ctry_code', sa.VARCHAR(3)),
    sa.Column('ctry_descp', sa.VARCHAR(220)),
    sa.Column('co_code', sa.VARCHAR(3)),
    sa.Column('co_descp', sa.VARCHAR(220)),
    sa.Column('cust_nbr', sa.INT()),
    sa.Column('rt_nbr', sa.INT()),
    sa.Column('chain_node_sys_nbr', sa.VARCHAR(8)),
    sa.Column('cust_loc_nbr', sa.INT()),
    sa.Column('bus_loc_str_addr1', sa.VARCHAR(35)),
    sa.Column('bus_loc_str_addr2', sa.VARCHAR(35)),
    sa.Column('bus_loc_city', sa.VARCHAR(20)),
    sa.Column('bus_loc_cnty_sburb', sa.VARCHAR(20)),
    sa.Column('bus_loc_st_prov', sa.VARCHAR(20)),
    sa.Column('bus_loc_ctry', sa.VARCHAR(20)),
    sa.Column('bus_loc_post_code', sa.VARCHAR(9)),
    sa.Column('contc_persn_nm', sa.VARCHAR(40)),
    sa.Column('cust_phone_nbr', sa.VARCHAR(15)),
    sa.Column('cust_fax_nbr', sa.VARCHAR(15)),
    sa.Column('contr_id', sa.VARCHAR(20)),
    sa.Column('prmy_cust_nbr', sa.INT()),
    sa.Column('first_sale_dt', sf.DATE()),
    sa.Column('most_rcnt_sale_dt', sf.DATE()),
    sa.Column('avg_wkly_sale_amt', sa.INT()),
    sa.Column('bus_type_code', sa.VARCHAR(1)),
    sa.Column('bus_type_descp', sa.VARCHAR(220)),
    sa.Column('facil_use_code', sa.VARCHAR(1)),
    sa.Column('facil_use_descp', sa.VARCHAR(220)),
    sa.Column('alt_cust_nbr', sa.INT()),
    sa.Column('alt_cust_nm', sa.VARCHAR(40)),
    sa.Column('cust_nm', sa.VARCHAR(40)),
    sa.Column('store_nbr', sa.VARCHAR(6)),
    sa.Column('dept_code', sa.VARCHAR(2)),
    sa.Column('cust_legal_nm', sa.VARCHAR(50)),
    sa.Column('cust_stat_code', sa.SMALLINT()),
    sa.Column('trade_seg_code', sa.VARCHAR(2)),
    sa.Column('trade_seg_descp', sa.VARCHAR(20)),
    sa.Column('trade_chanl_code', sa.VARCHAR(2)),
    sa.Column('trade_chanl_descp', sa.VARCHAR(20)),
    sa.Column('prstg_cust_flg', sa.VARCHAR(1)),
    sa.Column('cod_reasn_code', sa.SMALLINT()),
    sa.Column('cod_reasn_descp', sa.VARCHAR(220)),
    sa.Column('paymt_type_code', sa.SMALLINT()),
    sa.Column('paymt_type_descp', sa.VARCHAR(15)),
    sa.Column('bill_loc_nbr', sa.VARCHAR(18)),
    sa.Column('cr_risk_code', sa.VARCHAR(1)),
    sa.Column('cr_risk_descp', sa.VARCHAR(220)),
    sa.Column('cr_appv_stat_code', sa.VARCHAR(1)),
    sa.Column('cr_appv_stat_descp', sa.VARCHAR(220)),
    sa.Column('contr_disc_pct', sa.DECIMAL(5, 4)),
    sa.Column('auth_prod_list_nbr', sa.INT()),
    sa.Column('promo_lock_in_flg', sa.VARCHAR(1)),
    sa.Column('alowb_promo_code', sa.VARCHAR(1)),
    sa.Column('promo_pkg_type1', sa.SMALLINT()),
    sa.Column('promo_pkg_type1_descp', sa.VARCHAR(220)),
    sa.Column('promo_pkg_type2', sa.SMALLINT()),
    sa.Column('promo_pkg_type2_descp', sa.VARCHAR(220)),
    sa.Column('promo_pkg_type3', sa.SMALLINT()),
    sa.Column('promo_pkg_type3_descp', sa.VARCHAR(220)),
    sa.Column('promo_pkg_type4', sa.SMALLINT()),
    sa.Column('promo_pkg_type4_descp', sa.VARCHAR(220)),
    sa.Column('promo_pkg_type5', sa.SMALLINT()),
    sa.Column('promo_pkg_type5_descp', sa.VARCHAR(220)),
    sa.Column('serv_freq_code', sa.VARCHAR(1)),
    sa.Column('serv_freq_descp', sa.VARCHAR(220)),
    sa.Column('serv_wk_nbr', sa.SMALLINT()),
    sa.Column('serv_day_nbr', sa.VARCHAR(7)),
    sa.Column('indep_cust_flg', sa.VARCHAR(1)),
    sa.Column('prmy_qty_type_code', sa.VARCHAR(1)),
    sa.Column('own_code', sa.VARCHAR(1)),
    sa.Column('frhse_flg', sa.VARCHAR(1)),
    sa.Column('temp_cust_flg', sa.VARCHAR(1)),
    sa.Column('distrib_flg', sa.SMALLINT()),
    sa.Column('co_prmy_ft_qty', sa.SMALLINT()),
    sa.Column('co_fem_qty', sa.SMALLINT()),
    sa.Column('co_max_qty', sa.SMALLINT()),
    sa.Column('co_other_qty', sa.SMALLINT()),
    sa.Column('cmpet_prmy_ft_qty', sa.SMALLINT()),
    sa.Column('cmpet_fem_qty', sa.SMALLINT()),
    sa.Column('cmpet_max_qty', sa.SMALLINT()),
    sa.Column('cmpet_other_qty', sa.SMALLINT()),
    sa.Column('dspla_acct_flg', sa.VARCHAR(1)),
    sa.Column('store_dspla_txt', sa.VARCHAR(20)),
    sa.Column('scan_pay_flg', sa.VARCHAR(1)),
    sa.Column('dex_flg', sa.VARCHAR(1)),
    sa.Column('duns_nbr', sa.VARCHAR(9)),
    sa.Column('cust_bus_seg_code', sa.VARCHAR(2)),
    sa.Column('cust_bus_seg_descp', sa.VARCHAR(220)),
    sa.Column('clr_dir_deliv_flg', sa.VARCHAR(1)),
    sa.Column('mltry_cust_flg', sa.VARCHAR(1)),
    sa.Column('accpt_dflt_ck_flg', sa.VARCHAR(1)),
    sa.Column('are_class_code', sa.SMALLINT()),
    sa.Column('comm_type', sa.VARCHAR(2)),
    sa.Column('comm_type_descp', sa.VARCHAR(220)),
    sa.Column('unit_case_flg', sa.VARCHAR(1)),
    sa.Column('tdlinx_id', sa.VARCHAR(20)),
    sa.Column('tdlinx_trade_chanl', sa.VARCHAR(2)),
    sa.Column('prmy_equip_code', sa.VARCHAR(3)),
    sa.Column('cust_type_categ', sa.VARCHAR(3)),
    sa.Column('phy_loc_str_addr1', sa.VARCHAR(35)),
    sa.Column('phy_loc_str_addr2', sa.VARCHAR(35)),
    sa.Column('phy_loc_city', sa.VARCHAR(20)),
    sa.Column('phy_loc_cnty_sburb', sa.VARCHAR(20)),
    sa.Column('phy_loc_st_prov', sa.VARCHAR(20)),
    sa.Column('phy_loc_ctry', sa.VARCHAR(20)),
    sa.Column('phy_loc_post_code', sa.VARCHAR(9)),
    sa.Column('close_cross_str', sa.VARCHAR(60)),
    sa.Column('lat_code', sa.DECIMAL(38, 6)),
    sa.Column('lon_code', sa.DECIMAL(38, 6)),
    sa.Column('deliv_freq_code', sa.VARCHAR(1)),
    sa.Column('deliv_wk_nbr', sa.SMALLINT()),
    sa.Column('deliv_day_nbr', sa.VARCHAR(7)),
    sa.Column('cust_end_date', sf.DATE()),
    sa.Column('serv_incl_no_sale_freq_code', sa.VARCHAR(1)),
    sa.Column('serv_incl_no_sale_freq_descp', sa.VARCHAR(220)),
    sa.Column('serv_incl_no_sale_wk_nbr', sa.SMALLINT()),
    sa.Column('serv_incl_no_sale_day_nbr', sa.VARCHAR(7)),
    sa.Column('prod_deliv_freq_code', sa.VARCHAR(1)),
    sa.Column('prod_deliv_freq_descp', sa.VARCHAR(220)),
    sa.Column('prod_deliv_wk_nbr', sa.SMALLINT()),
    sa.Column('prod_deliv_day_nbr', sa.VARCHAR(7)),
    sa.Column('ship_note', sa.INT()),
    sa.Column('chain_lvl1_node_nbr', sa.VARCHAR(6)),
    sa.Column('chain_lvl1_node_nm', sa.VARCHAR(10)),
    sa.Column('chain_lvl2_key', sa.VARCHAR(12)),
    sa.Column('chain_lvl2_node_nbr', sa.VARCHAR(6)),
    sa.Column('chain_lvl2_node_nm', sa.VARCHAR(10)),
    sa.Column('chain_lvl3_key', sa.VARCHAR(18)),
    sa.Column('chain_lvl3_node_nbr', sa.VARCHAR(6)),
    sa.Column('chain_lvl3_node_nm', sa.VARCHAR(10)),
    sa.Column('chain_lvl4_key', sa.VARCHAR(24)),
    sa.Column('chain_lvl4_node_nbr', sa.VARCHAR(6)),
    sa.Column('chain_lvl4_node_nm', sa.VARCHAR(10)),
    sa.Column('chain_lvl5_key', sa.VARCHAR(30)),
    sa.Column('chain_lvl5_node_nbr', sa.VARCHAR(6)),
    sa.Column('chain_lvl5_node_nm', sa.VARCHAR(10)),
    sa.Column('chain_lvl6_key', sa.VARCHAR(36)),
    sa.Column('chain_lvl6_node_nbr', sa.VARCHAR(6)),
    sa.Column('chain_lvl6_node_nm', sa.VARCHAR(10)),
    sa.Column('cost_ctr', sa.VARCHAR(6)),
    sa.Column('geo_type_code', sa.VARCHAR(4)),
    sa.Column('geo_lvl4_contc_nm', sa.VARCHAR(30)),
    sa.Column('geo_lvl4_key', sa.VARCHAR(12)),
    sa.Column('geo_lvl4_node_nbr', sa.VARCHAR(4)),
    sa.Column('geo_lvl4_node_nm', sa.VARCHAR(30)),
    sa.Column('geo_lvl3_key', sa.VARCHAR(8)),
    sa.Column('geo_lvl3_node_nbr', sa.VARCHAR(3)),
    sa.Column('geo_lvl3_node_nm', sa.VARCHAR(30)),
    sa.Column('geo_lvl2_key', sa.VARCHAR(5)),
    sa.Column('geo_lvl2_node_nbr', sa.VARCHAR(3)),
    sa.Column('geo_lvl2_node_nm', sa.VARCHAR(30)),
    sa.Column('geo_lvl1_node_nbr', sa.VARCHAR(2)),
    sa.Column('geo_lvl1_node_nm', sa.VARCHAR(30)),
    sa.Column('struc_node_sys_nbr', sa.VARCHAR(6)),
    sa.Column('prmy_rt_empl_nbr', sa.VARCHAR(10)),
    sa.Column('prmy_rt_empl_nm', sa.VARCHAR(40)),
    sa.Column('rt_type_code', sa.VARCHAR(2)),
    sa.Column('rt_type_descp', sa.VARCHAR(20)),
    sa.Column('rt_type_code_elig_flg', sa.VARCHAR(12)),
    sa.Column('rt_loc_nbr', sa.INT()),
    sa.Column('rt_loc_nm', sa.VARCHAR(30)),
    sa.Column('rt_loc_st_prov', sa.VARCHAR(20)),
    sa.Column('rt_loc_type_code', sa.VARCHAR(2)),
    sa.Column('rt_loc_type_descp', sa.VARCHAR(25)),
    sa.Column('last_updt_dt', sf.TIMESTAMP_TZ())
)

##############################
#	fl_prod
##############################
op.create_table(
    'fl_prod',
    sa.Column('ctry_code', sa.VARCHAR(3)),
    sa.Column('co_code', sa.VARCHAR(3)),
    sa.Column('prod_upc', sa.INT()),
    sa.Column('prod_slbl', sa.INT()),
    sa.Column('prod_tkt_descp_txt', sa.VARCHAR(30)),
    sa.Column('prt_wt', sa.DECIMAL(9, 4)),
    sa.Column('sale_um_code', sa.VARCHAR(1)),
    sa.Column('sale_um_descp', sa.VARCHAR(3)),
    sa.Column('prod_type_code', sa.VARCHAR(3)),
    sa.Column('upc_mfg_id', sa.INT()),
    sa.Column('sale_class_code', sa.VARCHAR(3)),
    sa.Column('sale_class_descp', sa.VARCHAR(25)),
    sa.Column('size_code', sa.VARCHAR(3)),
    sa.Column('size_descp', sa.VARCHAR(25)),
    sa.Column('flvr_code', sa.VARCHAR(3)),
    sa.Column('flvr_descp', sa.VARCHAR(25)),
    sa.Column('bdc_descp', sa.VARCHAR(25)),
    sa.Column('bus_unit_code', sa.VARCHAR(3)),
    sa.Column('bus_unit_descp', sa.VARCHAR(20)),
    sa.Column('bus_unit_seq_nbr', sa.DECIMAL(3, 0)),
    sa.Column('sub_categ_code', sa.VARCHAR(3)),
    sa.Column('sub_categ_descp', sa.VARCHAR(20)),
    sa.Column('sub_categ_seq_nbr', sa.DECIMAL(3, 0)),
    sa.Column('categ_code', sa.VARCHAR(3)),
    sa.Column('categ_descp', sa.VARCHAR(20)),
    sa.Column('categ_seq_nbr', sa.DECIMAL(3, 0)),
    sa.Column('mfg_class_code', sa.VARCHAR(3)),
    sa.Column('mfg_class_descp', sa.VARCHAR(30)),
    sa.Column('case_nbr', sa.DECIMAL(4, 0)),
    sa.Column('case_qty', sa.DECIMAL(4, 0)),
    sa.Column('brand_code', sa.VARCHAR(3)),
    sa.Column('brand_descp', sa.VARCHAR(25)),
    sa.Column('distr_chanl', sa.VARCHAR(3)),
    sa.Column('cdsd_item_tempr', sa.VARCHAR(3)),
    sa.Column('cdsd_prmy_sell_um', sa.VARCHAR(3)),
    sa.Column('cdsd_serv_type_code', sa.VARCHAR(3)),
    sa.Column('cdsd_purch_type_code', sa.VARCHAR(3)),
    sa.Column('bdc_code', sa.VARCHAR(9)),
    sa.Column('pkg_type_code', sa.VARCHAR(3)),
    sa.Column('pkg_type_desc', sa.VARCHAR(25)),
    sa.Column('pkg_indic', sa.SMALLINT()),
    sa.Column('ck_digit', sa.SMALLINT()),
    sa.Column('mfg_id_len', sa.SMALLINT()),
    sa.Column('upc_len', sa.SMALLINT()),
    sa.Column('gtin', sa.VARCHAR(14)),
    sa.Column('case_type_code', sa.VARCHAR(3)),
    sa.Column('cdy_per_case', sa.DECIMAL(4, 0)),
    sa.Column('last_updt_dt', sf.TIMESTAMP_TZ())
)

##############################
#	fl_sales_2020
##############################
op.create_table(
    'fl_sales_2020',
    sa.Column('cust_nbr', sa.INT()),
    sa.Column('prod_upc', sa.INT()),
    sa.Column('prod_slbl', sa.INT()),
    sa.Column('sale_tkt_yr', sa.VARCHAR(4)),
    sa.Column('sale_tkt_pd', sa.VARCHAR(2)),
    sa.Column('sale_tkt_wk', sa.VARCHAR(1)),
    sa.Column('sale_tkt_wk_end_dt', sf.DATE()),
    sa.Column('tkt_sale_amt', sa.DECIMAL(18, 4)),
    sa.Column('tkt_sale_qty', sa.BIGINT()),
    sa.Column('tkt_sale_wt', sa.DECIMAL(18, 4)),
    sa.Column('gross_tkt_sale_amt', sa.DECIMAL(18, 4)),
    sa.Column('gross_tkt_sale_qty', sa.BIGINT()),
    sa.Column('gross_tkt_sale_wt', sa.DECIMAL(18, 4)),
    sa.Column('net_tkt_sale_amt', sa.DECIMAL(18, 4)),
    sa.Column('net_tkt_sale_qty', sa.BIGINT()),
    sa.Column('net_tkt_sale_wt', sa.DECIMAL(18, 4)),
    sa.Column('am_promo_allow_amt', sa.DECIMAL(18, 4)),
    sa.Column('am_promo_sale_amt', sa.DECIMAL(18, 4)),
    sa.Column('am_promo_sale_qty', sa.BIGINT()),
    sa.Column('full_revnu_sale_amt', sa.DECIMAL(18, 4)),
    sa.Column('full_revnu_sale_qty', sa.BIGINT()),
    sa.Column('last_updt_dt', sf.TIMESTAMP_TZ())
)

##############################
#	fl_sales_2021
##############################
op.create_table(
    'fl_sales_2021',
    sa.Column('cust_nbr', sa.INT()),
    sa.Column('prod_upc', sa.INT()),
    sa.Column('prod_slbl', sa.INT()),
    sa.Column('sale_tkt_yr', sa.VARCHAR(4)),
    sa.Column('sale_tkt_pd', sa.VARCHAR(2)),
    sa.Column('sale_tkt_wk', sa.VARCHAR(1)),
    sa.Column('sale_tkt_wk_end_dt', sf.DATE()),
    sa.Column('tkt_sale_amt', sa.DECIMAL(18, 4)),
    sa.Column('tkt_sale_qty', sa.BIGINT()),
    sa.Column('tkt_sale_wt', sa.DECIMAL(18, 4)),
    sa.Column('gross_tkt_sale_amt', sa.DECIMAL(18, 4)),
    sa.Column('gross_tkt_sale_qty', sa.BIGINT()),
    sa.Column('gross_tkt_sale_wt', sa.DECIMAL(18, 4)),
    sa.Column('net_tkt_sale_amt', sa.DECIMAL(18, 4)),
    sa.Column('net_tkt_sale_qty', sa.BIGINT()),
    sa.Column('net_tkt_sale_wt', sa.DECIMAL(18, 4)),
    sa.Column('am_promo_allow_amt', sa.DECIMAL(18, 4)),
    sa.Column('am_promo_sale_amt', sa.DECIMAL(18, 4)),
    sa.Column('am_promo_sale_qty', sa.BIGINT()),
    sa.Column('full_revnu_sale_amt', sa.DECIMAL(18, 4)),
    sa.Column('full_revnu_sale_qty', sa.BIGINT()),
    sa.Column('last_updt_dt', sf.TIMESTAMP_TZ())
)

##############################
#	fl_sales_2019
##############################
op.create_table(
    'fl_sales_2019',
    sa.Column('cust_nbr', sa.INT()),
    sa.Column('prod_upc', sa.INT()),
    sa.Column('prod_slbl', sa.INT()),
    sa.Column('sale_tkt_yr', sa.VARCHAR(4)),
    sa.Column('sale_tkt_pd', sa.VARCHAR(2)),
    sa.Column('sale_tkt_wk', sa.VARCHAR(1)),
    sa.Column('sale_tkt_wk_end_dt', sf.DATE()),
    sa.Column('tkt_sale_amt', sa.DECIMAL(18, 4)),
    sa.Column('tkt_sale_qty', sa.BIGINT()),
    sa.Column('tkt_sale_wt', sa.DECIMAL(18, 4)),
    sa.Column('gross_tkt_sale_amt', sa.DECIMAL(18, 4)),
    sa.Column('gross_tkt_sale_qty', sa.BIGINT()),
    sa.Column('gross_tkt_sale_wt', sa.DECIMAL(18, 4)),
    sa.Column('net_tkt_sale_amt', sa.DECIMAL(18, 4)),
    sa.Column('net_tkt_sale_qty', sa.BIGINT()),
    sa.Column('net_tkt_sale_wt', sa.DECIMAL(18, 4)),
    sa.Column('am_promo_allow_amt', sa.DECIMAL(18, 4)),
    sa.Column('am_promo_sale_amt', sa.DECIMAL(18, 4)),
    sa.Column('am_promo_sale_qty', sa.BIGINT()),
    sa.Column('full_revnu_sale_amt', sa.DECIMAL(18, 4)),
    sa.Column('full_revnu_sale_qty', sa.BIGINT()),
    sa.Column('last_updt_dt', sf.TIMESTAMP_TZ())
)

##############################
#	fl_sales_2018
##############################
op.create_table(
    'fl_sales_2018',
    sa.Column('cust_nbr', sa.INT()),
    sa.Column('prod_upc', sa.INT()),
    sa.Column('prod_slbl', sa.INT()),
    sa.Column('sale_tkt_yr', sa.VARCHAR(4)),
    sa.Column('sale_tkt_pd', sa.VARCHAR(2)),
    sa.Column('sale_tkt_wk', sa.VARCHAR(1)),
    sa.Column('sale_tkt_wk_end_dt', sf.DATE()),
    sa.Column('tkt_sale_amt', sa.DECIMAL(18, 4)),
    sa.Column('tkt_sale_qty', sa.BIGINT()),
    sa.Column('tkt_sale_wt', sa.DECIMAL(18, 4)),
    sa.Column('gross_tkt_sale_amt', sa.DECIMAL(18, 4)),
    sa.Column('gross_tkt_sale_qty', sa.BIGINT()),
    sa.Column('gross_tkt_sale_wt', sa.DECIMAL(18, 4)),
    sa.Column('net_tkt_sale_amt', sa.DECIMAL(18, 4)),
    sa.Column('net_tkt_sale_qty', sa.BIGINT()),
    sa.Column('net_tkt_sale_wt', sa.DECIMAL(18, 4)),
    sa.Column('am_promo_allow_amt', sa.DECIMAL(18, 4)),
    sa.Column('am_promo_sale_amt', sa.DECIMAL(18, 4)),
    sa.Column('am_promo_sale_qty', sa.BIGINT()),
    sa.Column('full_revnu_sale_amt', sa.DECIMAL(18, 4)),
    sa.Column('full_revnu_sale_qty', sa.BIGINT()),
    sa.Column('last_updt_dt', sf.TIMESTAMP_TZ())
)

##############################
#	pbc_cust
##############################
op.create_table(
    'pbc_cust',
    sa.Column('cust_id', sa.INT()),
    sa.Column('bulk_dely_flg', sa.VARCHAR(1)),
    sa.Column('chain_flg', sa.VARCHAR(1)),
    sa.Column('chain_owner_cde', sa.VARCHAR(3)),
    sa.Column('chain_owner_desc', sa.VARCHAR(35)),
    sa.Column('cur_stat_cde', sa.VARCHAR(3)),
    sa.Column('cur_stat_desc', sa.VARCHAR(15)),
    sa.Column('cur_stat_dte', sf.DATE()),
    sa.Column('cust_prod_flg', sa.VARCHAR(1)),
    sa.Column('cust_serv_flg', sa.VARCHAR(1)),
    sa.Column('cust_org_flg', sa.VARCHAR(1)),
    sa.Column('cust_blg_flg', sa.VARCHAR(1)),
    sa.Column('cust_misc_flg', sa.VARCHAR(1)),
    sa.Column('cust_added_dte', sf.DATE()),
    sa.Column('cust_lglnme', sa.VARCHAR(17)),
    sa.Column('lang_cde', sa.VARCHAR(3)),
    sa.Column('lang_desc', sa.VARCHAR(35)),
    sa.Column('loc_prod_id', sa.INT()),
    sa.Column('loc_serv_id', sa.INT()),
    sa.Column('nme', sa.VARCHAR(35)),
    sa.Column('natl_acct_flg', sa.VARCHAR(1)),
    sa.Column('po_reqd_flg', sa.VARCHAR(1)),
    sa.Column('pymt_term_beg_dte', sf.DATE()),
    sa.Column('pymt_term_cde', sa.VARCHAR(3)),
    sa.Column('pymt_term_desc', sa.VARCHAR(35)),
    sa.Column('sep_inv_flg', sa.VARCHAR(1)),
    sa.Column('tax_exempt_num', sa.VARCHAR(14)),
    sa.Column('tin_num', sa.VARCHAR(15)),
    sa.Column('tin_type_cde', sa.VARCHAR(3)),
    sa.Column('tin_type_desc', sa.VARCHAR(35)),
    sa.Column('empl_tac_id', sa.INT()),
    sa.Column('cust_equip_flg', sa.VARCHAR(1)),
    sa.Column('udf_num', sa.VARCHAR(25)),
    sa.Column('vrtx_geo_cde', sa.INT()),
    sa.Column('bus_type_cde', sa.VARCHAR(3)),
    sa.Column('bus_type_desc', sa.VARCHAR(35)),
    sa.Column('tme_zone_cde', sa.VARCHAR(3)),
    sa.Column('tme_zone_desc', sa.VARCHAR(35)),
    sa.Column('cust_fobo_btlr_flg', sa.VARCHAR(1)),
    sa.Column('cust_fobo_cust_flg', sa.VARCHAR(1)),
    sa.Column('cust_fsv_flg', sa.VARCHAR(1)),
    sa.Column('prc_zone_id', sa.INT()),
    sa.Column('ethnic_cde', sa.VARCHAR(3)),
    sa.Column('ethnic_desc', sa.VARCHAR(35)),
    sa.Column('cust_ucs_cmctn_id', sa.VARCHAR(10)),
    sa.Column('cust_dab_num', sa.INT()),
    sa.Column('cust_dex_beg_dte', sf.DATE()),
    sa.Column('leg_chain_num', sa.INT()),
    sa.Column('seas_clsd_beg_dte', sf.DATE()),
    sa.Column('seas_clsd_end_dte', sf.DATE()),
    sa.Column('cust_lgtud_num', sa.DECIMAL(15, 0)),
    sa.Column('cust_latud_num', sa.DECIMAL(15, 0)),
    sa.Column('bus_type_aggr_cde', sa.VARCHAR(3)),
    sa.Column('bus_type_aggr_desc', sa.VARCHAR(35)),
    sa.Column('outside_city_lmt_ind', sa.SMALLINT()),
    sa.Column('cust_last_actvty_dte', sf.DATE()),
    sa.Column('grp1_type_desc', sa.VARCHAR(35)),
    sa.Column('grp1_ownr_id', sa.INT()),
    sa.Column('grp1_ownr_desc', sa.VARCHAR(35)),
    sa.Column('grp1_lvl_1_id', sa.INT()),
    sa.Column('grp1_lvl_1_desc', sa.VARCHAR(35)),
    sa.Column('grp1_lvl_2_id', sa.INT()),
    sa.Column('grp1_lvl_2_desc', sa.VARCHAR(35)),
    sa.Column('grp2_type_desc', sa.VARCHAR(35)),
    sa.Column('grp2_ownr_id', sa.INT()),
    sa.Column('grp2_ownr_desc', sa.VARCHAR(35)),
    sa.Column('grp2_lvl_1_ancstr_id', sa.INT()),
    sa.Column('grp2_lvl_1_ancstr_nme', sa.VARCHAR(35)),
    sa.Column('grp2_lvl_1_ancstr_prev_nme', sa.VARCHAR(35)),
    sa.Column('grp2_lvl_1_id', sa.INT()),
    sa.Column('grp2_lvl_1_desc', sa.VARCHAR(35)),
    sa.Column('grp2_lvl_2_id', sa.INT()),
    sa.Column('grp2_lvl_2_desc', sa.VARCHAR(35)),
    sa.Column('grp3_type_desc', sa.VARCHAR(35)),
    sa.Column('grp3_ownr_id', sa.INT()),
    sa.Column('grp3_ownr_desc', sa.VARCHAR(35)),
    sa.Column('grp3_lvl_1_id', sa.INT()),
    sa.Column('grp3_lvl_1_desc', sa.VARCHAR(35)),
    sa.Column('grp3_lvl_2_id', sa.INT()),
    sa.Column('grp3_lvl_2_desc', sa.VARCHAR(35)),
    sa.Column('loc_prod_nme', sa.VARCHAR(35)),
    sa.Column('loc_prod_mu_id', sa.INT()),
    sa.Column('loc_prod_mu_nme', sa.VARCHAR(35)),
    sa.Column('loc_prod_bu_id', sa.INT()),
    sa.Column('loc_prod_bu_nme', sa.VARCHAR(35)),
    sa.Column('loc_prod_area_rpt_id', sa.INT()),
    sa.Column('loc_prod_area_rpt_nme', sa.VARCHAR(35)),
    sa.Column('loc_prod_mu_rpt_id', sa.INT()),
    sa.Column('loc_prod_mu_rpt_nme', sa.VARCHAR(35)),
    sa.Column('loc_prod_bu_rpt_id', sa.INT()),
    sa.Column('loc_prod_bu_rpt_nme', sa.VARCHAR(35)),
    sa.Column('loc_serv_nme', sa.VARCHAR(35)),
    sa.Column('loc_serv_mu_id', sa.INT()),
    sa.Column('loc_serv_mu_nme', sa.VARCHAR(35)),
    sa.Column('loc_serv_bu_id', sa.INT()),
    sa.Column('loc_serv_bu_nme', sa.VARCHAR(35)),
    sa.Column('loc_serv_area_rpt_id', sa.INT()),
    sa.Column('loc_serv_area_rpt_nme', sa.VARCHAR(35)),
    sa.Column('loc_serv_mu_rpt_id', sa.INT()),
    sa.Column('loc_serv_mu_rpt_nme', sa.VARCHAR(35)),
    sa.Column('loc_serv_bu_rpt_id', sa.INT()),
    sa.Column('loc_serv_bu_rpt_nme', sa.VARCHAR(35)),
    sa.Column('bus_type_ctgy_cde', sa.VARCHAR(3)),
    sa.Column('bus_type_ctgy_desc', sa.VARCHAR(35)),
    sa.Column('grp4_type_desc', sa.VARCHAR(35)),
    sa.Column('grp4_ownr_id', sa.INT()),
    sa.Column('grp4_ownr_desc', sa.VARCHAR(35)),
    sa.Column('grp4_lvl_1_id', sa.INT()),
    sa.Column('grp4_lvl_1_desc', sa.VARCHAR(35)),
    sa.Column('grp4_lvl_2_id', sa.INT()),
    sa.Column('grp4_lvl_2_desc', sa.VARCHAR(35)),
    sa.Column('dex_vers_num', sa.VARCHAR(10)),
    sa.Column('dely_adr_city', sa.VARCHAR(28)),
    sa.Column('dely_adr_cntry_cde', sa.VARCHAR(3)),
    sa.Column('dely_adr_cnty', sa.VARCHAR(25)),
    sa.Column('dely_adr_state', sa.VARCHAR(2)),
    sa.Column('dely_adr_strt1', sa.VARCHAR(35)),
    sa.Column('dely_adr_strt2', sa.VARCHAR(35)),
    sa.Column('dely_adr_strt3', sa.VARCHAR(35)),
    sa.Column('dely_adr_zip', sa.VARCHAR(9)),
    sa.Column('blg_adr_city', sa.VARCHAR(28)),
    sa.Column('blg_adr_cntry_cde', sa.VARCHAR(3)),
    sa.Column('blg_adr_cnty', sa.VARCHAR(25)),
    sa.Column('blg_adr_state', sa.VARCHAR(2)),
    sa.Column('blg_adr_strt1', sa.VARCHAR(35)),
    sa.Column('blg_adr_strt2', sa.VARCHAR(35)),
    sa.Column('blg_adr_strt3', sa.VARCHAR(35)),
    sa.Column('blg_adr_zip', sa.VARCHAR(9)),
    sa.Column('mlg_adr_city', sa.VARCHAR(28)),
    sa.Column('mlg_adr_cntry_cde', sa.VARCHAR(3)),
    sa.Column('mlg_adr_cnty', sa.VARCHAR(25)),
    sa.Column('mlg_adr_state', sa.VARCHAR(2)),
    sa.Column('mlg_adr_strt1', sa.VARCHAR(35)),
    sa.Column('mlg_adr_strt2', sa.VARCHAR(35)),
    sa.Column('mlg_adr_strt3', sa.VARCHAR(35)),
    sa.Column('mlg_adr_zip', sa.VARCHAR(9)),
    sa.Column('sls_cnct_first_nme', sa.VARCHAR(17)),
    sa.Column('sls_cnct_last_nme', sa.VARCHAR(17)),
    sa.Column('sls_cnct_phone_acd_num', sa.VARCHAR(3)),
    sa.Column('sls_cnct_phone_num', sa.VARCHAR(7)),
    sa.Column('sls_cnct_phone_ext_num', sa.VARCHAR(4)),
    sa.Column('rpr_cnct_first_nme', sa.VARCHAR(17)),
    sa.Column('rpr_cnct_last_nme', sa.VARCHAR(17)),
    sa.Column('rpr_cnct_phone_acd_num', sa.VARCHAR(3)),
    sa.Column('rpr_cnct_phone_num', sa.VARCHAR(7)),
    sa.Column('rpr_cnct_phone_ext_num', sa.VARCHAR(4)),
    sa.Column('ts_cnct_first_nme', sa.VARCHAR(17)),
    sa.Column('ts_cnct_last_nme', sa.VARCHAR(17)),
    sa.Column('ts_cnct_phone_acd_num', sa.VARCHAR(3)),
    sa.Column('ts_cnct_phone_num', sa.VARCHAR(7)),
    sa.Column('ts_cnct_phone_ext_num', sa.VARCHAR(4)),
    sa.Column('fsv_cnct_first_nme', sa.VARCHAR(17)),
    sa.Column('fsv_cnct_last_nme', sa.VARCHAR(17)),
    sa.Column('fsv_cnct_phone_acd_num', sa.VARCHAR(3)),
    sa.Column('fsv_cnct_phone_num', sa.VARCHAR(7)),
    sa.Column('fsv_cnct_phone_ext_num', sa.VARCHAR(4)),
    sa.Column('merch_acct_flg', sa.VARCHAR(1)),
    sa.Column('min_ord_qty', sa.SMALLINT()),
    sa.Column('chrg_to_frnch', sa.VARCHAR(5)),
    sa.Column('inv_udf_num_cde', sa.VARCHAR(3)),
    sa.Column('inv_udf_num_desc', sa.VARCHAR(35)),
    sa.Column('dw_srce_id', sa.INT()),
    sa.Column('dw_updt_dte', sf.DATE()),
    sa.Column('actv_dely_loc_id', sa.INT()),
    sa.Column('cust_cmnt_txt', sa.VARCHAR(255)),
    sa.Column('cust_origtn_cde', sa.VARCHAR(3)),
    sa.Column('last_updt_dt', sf.TIMESTAMP_TZ())
)

##############################
#	pbc_prod
##############################
op.create_table(
    'pbc_prod',
    sa.Column('inven_id', sa.INT()),
    sa.Column('inven_dply_grp_nme', sa.VARCHAR(17)),
    sa.Column('brnd_id', sa.INT()),
    sa.Column('pkg_id', sa.INT()),
    sa.Column('inven_type_cde', sa.VARCHAR(3)),
    sa.Column('inven_type_desc', sa.VARCHAR(35)),
    sa.Column('nme', sa.VARCHAR(35)),
    sa.Column('inven_dply_seq_num', sa.DECIMAL(15, 0)),
    sa.Column('inven_dply_grp_seq', sa.DECIMAL(15, 0)),
    sa.Column('inven_dply_nme', sa.VARCHAR(17)),
    sa.Column('purch_ctgy_id', sa.VARCHAR(10)),
    sa.Column('ord_ref_num', sa.VARCHAR(35)),
    sa.Column('inven_uom_cde', sa.VARCHAR(4)),
    sa.Column('inven_uom_desc', sa.VARCHAR(35)),
    sa.Column('create_dte', sf.DATE()),
    sa.Column('upc_cde', sa.VARCHAR(12)),
    sa.Column('inven_sfty_stk_pct', sa.DOUBLE()),
    sa.Column('prod_mix_cde', sa.VARCHAR(3)),
    sa.Column('prod_mix_desc', sa.VARCHAR(35)),
    sa.Column('prod_grp_cde', sa.VARCHAR(3)),
    sa.Column('prod_grp_desc', sa.VARCHAR(35)),
    sa.Column('prod_type_cde', sa.VARCHAR(3)),
    sa.Column('prod_type_desc', sa.VARCHAR(35)),
    sa.Column('avg_flr_cost_amt', sa.DOUBLE()),
    sa.Column('std_wgt_qty', sa.DOUBLE()),
    sa.Column('natl_acct_cde', sa.VARCHAR(3)),
    sa.Column('natl_acct_desc', sa.VARCHAR(35)),
    sa.Column('prod_8oz_conv_fctr', sa.DOUBLE()),
    sa.Column('conc_mark_up_amt', sa.DOUBLE()),
    sa.Column('sply_type_cde', sa.VARCHAR(3)),
    sa.Column('sply_type_desc', sa.VARCHAR(35)),
    sa.Column('serv_type_cde', sa.VARCHAR(3)),
    sa.Column('serv_type_desc', sa.VARCHAR(35)),
    sa.Column('brnd_nme', sa.VARCHAR(35)),
    sa.Column('trdmrk_cde', sa.VARCHAR(3)),
    sa.Column('trdmrk_desc', sa.VARCHAR(35)),
    sa.Column('flvr_cde', sa.VARCHAR(10)),
    sa.Column('flvr_desc', sa.VARCHAR(35)),
    sa.Column('corp_cde', sa.VARCHAR(3)),
    sa.Column('corp_desc', sa.VARCHAR(35)),
    sa.Column('ctgy_type_cde', sa.VARCHAR(3)),
    sa.Column('ctgy_type_desc', sa.VARCHAR(35)),
    sa.Column('caff_flg', sa.VARCHAR(1)),
    sa.Column('brnd_juice_pct', sa.DOUBLE()),
    sa.Column('brnd_shrt_nme', sa.VARCHAR(17)),
    sa.Column('brnd_swtnr_cde', sa.VARCHAR(3)),
    sa.Column('brnd_swtnr_desc', sa.VARCHAR(35)),
    sa.Column('pkg_nr_flag', sa.VARCHAR(1)),
    sa.Column('clust_cde', sa.VARCHAR(3)),
    sa.Column('clust_desc', sa.VARCHAR(35)),
    sa.Column('clust_qty', sa.INT()),
    sa.Column('config_qty', sa.INT()),
    sa.Column('pkg_nme', sa.VARCHAR(35)),
    sa.Column('pkg_shrt_nme', sa.VARCHAR(17)),
    sa.Column('rpt_pkg_id', sa.INT()),
    sa.Column('cont_cde', sa.VARCHAR(3)),
    sa.Column('cont_desc', sa.VARCHAR(35)),
    sa.Column('cont_uom_cde', sa.VARCHAR(3)),
    sa.Column('cont_uom_desc', sa.VARCHAR(35)),
    sa.Column('cont_uom_qty', sa.DOUBLE()),
    sa.Column('cont_nr_flag', sa.VARCHAR(1)),
    sa.Column('pkg_cont_mtrl_cde', sa.VARCHAR(3)),
    sa.Column('pkg_cont_mtrl_desc', sa.VARCHAR(35)),
    sa.Column('pkg_clstr_mtrl_cde', sa.VARCHAR(3)),
    sa.Column('pkg_clstr_mtrl_desc', sa.VARCHAR(35)),
    sa.Column('pkg_mtrl_cde', sa.VARCHAR(3)),
    sa.Column('pkg_mtl_desc', sa.VARCHAR(35)),
    sa.Column('pkg_cont_st_dp_flg', sa.VARCHAR(1)),
    sa.Column('logo_id', sa.INT()),
    sa.Column('logo_desc', sa.VARCHAR(35)),
    sa.Column('hrzn_prod_grp_id', sa.INT()),
    sa.Column('hrzn_prod_grp_desc', sa.VARCHAR(35)),
    sa.Column('hrzn_pkg_grp_id', sa.INT()),
    sa.Column('hrzn_pkg_grp_desc', sa.VARCHAR(35)),
    sa.Column('hrzn_prod_ctgy_id', sa.INT()),
    sa.Column('hrzn_prod_ctgy_desc', sa.VARCHAR(35)),
    sa.Column('hrzn_brnd_ctgy_id', sa.INT()),
    sa.Column('hrzn_brnd_ctgy_desc', sa.VARCHAR(35)),
    sa.Column('hrzn_pkg_ctgy_id', sa.INT()),
    sa.Column('hrzn_pkg_ctgy_desc', sa.VARCHAR(35)),
    sa.Column('hrzn_pkg_aggr_id', sa.INT()),
    sa.Column('hrzn_pkg_aggr_desc', sa.VARCHAR(35)),
    sa.Column('hrzn_corp_aggr_id', sa.INT()),
    sa.Column('hrzn_corp_aggr_desc', sa.VARCHAR(35)),
    sa.Column('case_upc_cde', sa.VARCHAR(12)),
    sa.Column('hrzn_pkg_cont_ctgy_id', sa.INT()),
    sa.Column('hrzn_pkg_cont_ctgy_desc', sa.VARCHAR(35)),
    sa.Column('hrzn_brnd_pkg_list_id', sa.INT()),
    sa.Column('hrzn_brnd_pkg_list_desc', sa.VARCHAR(35)),
    sa.Column('hrzn_brnd_pkg_summ_id', sa.INT()),
    sa.Column('hrzn_brnd_pkg_summ_desc', sa.VARCHAR(35)),
    sa.Column('hrzn_pkg_gm_id', sa.INT()),
    sa.Column('hrzn_pkg_gm_desc', sa.VARCHAR(35)),
    sa.Column('hrzn_pkg_summ_id', sa.INT()),
    sa.Column('hrzn_pkg_summ_desc', sa.VARCHAR(35)),
    sa.Column('comm_pkg_grp1_id', sa.INT()),
    sa.Column('comm_pkg_grp1_nme', sa.VARCHAR(35)),
    sa.Column('comm_pkg_grp2_id', sa.INT()),
    sa.Column('comm_pkg_grp2_nme', sa.VARCHAR(35)),
    sa.Column('hrzn_brnd_gm_id', sa.INT()),
    sa.Column('hrzn_brnd_gm_desc', sa.VARCHAR(35)),
    sa.Column('hrzn_brnd_trdmrk_id', sa.INT()),
    sa.Column('hrzn_brnd_trdmrk_desc', sa.VARCHAR(35)),
    sa.Column('hrzn_brnd_summ_id', sa.INT()),
    sa.Column('hrzn_brnd_summ_desc', sa.VARCHAR(35)),
    sa.Column('pbg_utilized_flg', sa.VARCHAR(1)),
    sa.Column('case_conv_fctr', sa.DECIMAL(13, 5)),
    sa.Column('lcl_case_conv_fctr', sa.DECIMAL(13, 5)),
    sa.Column('prod_best_taste_wk_qty', sa.DECIMAL(13, 4)),
    sa.Column('delete_flg', sa.VARCHAR(1)),
    sa.Column('mkt_ctgy_id', sa.INT()),
    sa.Column('mkt_ctgy_desc', sa.VARCHAR(35)),
    sa.Column('mkt_trdmrk_id', sa.INT()),
    sa.Column('mkt_trdmrk_desc', sa.VARCHAR(35)),
    sa.Column('pkg_cont_mtrl_grp_id', sa.INT()),
    sa.Column('pkg_cont_mtrl_grp_desc', sa.VARCHAR(35)),
    sa.Column('entrprs_initiv_01_id', sa.INT()),
    sa.Column('entrprs_initiv_01_nme', sa.VARCHAR(100)),
    sa.Column('entrprs_initiv_01_desc', sa.VARCHAR(35)),
    sa.Column('entrprs_initiv_02_id', sa.INT()),
    sa.Column('entrprs_initiv_02_nme', sa.VARCHAR(100)),
    sa.Column('entrprs_initiv_02_desc', sa.VARCHAR(35)),
    sa.Column('apxig_id', sa.INT()),
    sa.Column('apxig_nme', sa.VARCHAR(35)),
    sa.Column('dw_srce_id', sa.INT()),
    sa.Column('dw_updt_dte', sf.DATE()),
    sa.Column('comm_asm_grp_id', sa.INT()),
    sa.Column('comm_asm_grp_nme', sa.VARCHAR(35)),
    sa.Column('comm_cnvntl_drvr_grp_id', sa.INT()),
    sa.Column('comm_cnvntl_drvr_grp_nme', sa.VARCHAR(35)),
    sa.Column('comm_fsv_drvr_grp_id', sa.INT()),
    sa.Column('comm_fsv_drvr_grp_nme', sa.VARCHAR(35)),
    sa.Column('comm_psell_drvr_grp_id', sa.INT()),
    sa.Column('comm_psell_drvr_grp_nme', sa.VARCHAR(35)),
    sa.Column('pkg_wdth_unit_qty', sa.DECIMAL(13, 4)),
    sa.Column('pkg_hgt_unit_qty', sa.DECIMAL(13, 4)),
    sa.Column('pkg_lngth_unit_qty', sa.DECIMAL(13, 4)),
    sa.Column('pkg_dim_uofm_cde', sa.VARCHAR(4)),
    sa.Column('pkg_frnt_dim_cde', sa.VARCHAR(3)),
    sa.Column('pkg_stkblty_cde', sa.VARCHAR(3)),
    sa.Column('prod_wgt_unit_qty', sa.DECIMAL(13, 4)),
    sa.Column('prod_wgt_uofm_cde', sa.VARCHAR(4)),
    sa.Column('rfrg_reqd_flg', sa.VARCHAR(1)),
    sa.Column('last_updt_dt', sf.TIMESTAMP_TZ())
)

##############################
#	pbc_sales_2020
##############################
op.create_table(
    'pbc_sales_2020',
    sa.Column('cust_id', sa.INT()),
    sa.Column('inven_id', sa.INT()),
    sa.Column('fscl_yr_num', sa.SMALLINT()),
    sa.Column('fscl_pd_num', sa.SMALLINT()),
    sa.Column('fscl_wk_in_pd_num', sa.SMALLINT()),
    sa.Column('fscl_wk_end_dte', sf.DATE()),
    sa.Column('dely_lne_qty', sa.DECIMAL(18, 2)),
    sa.Column('raw_vol', sa.DECIMAL(18, 2)),
    sa.Column('eght_oz_vol', sa.DECIMAL(18, 2)),
    sa.Column('net_rev', sa.DECIMAL(18, 2)),
    sa.Column('last_updt_dt', sf.TIMESTAMP_TZ())
)

##############################
#	pbc_sales_2021
##############################
op.create_table(
    'pbc_sales_2021',
    sa.Column('cust_id', sa.INT()),
    sa.Column('inven_id', sa.INT()),
    sa.Column('fscl_yr_num', sa.SMALLINT()),
    sa.Column('fscl_pd_num', sa.SMALLINT()),
    sa.Column('fscl_wk_in_pd_num', sa.SMALLINT()),
    sa.Column('fscl_wk_end_dte', sf.DATE()),
    sa.Column('dely_lne_qty', sa.DECIMAL(18, 2)),
    sa.Column('raw_vol', sa.DECIMAL(18, 2)),
    sa.Column('eght_oz_vol', sa.DECIMAL(18, 2)),
    sa.Column('net_rev', sa.DECIMAL(18, 2)),
    sa.Column('last_updt_dt', sf.TIMESTAMP_TZ())
)

##############################
#	pbc_sales_2019
##############################
op.create_table(
    'pbc_sales_2019',
    sa.Column('cust_id', sa.INT()),
    sa.Column('inven_id', sa.INT()),
    sa.Column('fscl_yr_num', sa.SMALLINT()),
    sa.Column('fscl_pd_num', sa.SMALLINT()),
    sa.Column('fscl_wk_in_pd_num', sa.SMALLINT()),
    sa.Column('fscl_wk_end_dte', sf.DATE()),
    sa.Column('dely_lne_qty', sa.DECIMAL(18, 2)),
    sa.Column('raw_vol', sa.DECIMAL(18, 2)),
    sa.Column('eght_oz_vol', sa.DECIMAL(18, 2)),
    sa.Column('net_rev', sa.DECIMAL(18, 2)),
    sa.Column('last_updt_dt', sf.TIMESTAMP_TZ())
)

##############################
#	gsc_msa_demo
##############################
op.create_table(
    'gsc_msa_demo',
    sa.Column('msa_id', sa.VARCHAR(100)),
    sa.Column('minutes_num', sa.DECIMAL(5, 2)),
    sa.Column('pptotal_num', sa.INT()),
    sa.Column('pprhisp_num', sa.INT()),
    sa.Column('pprwhite_num', sa.INT()),
    sa.Column('pprblack_num', sa.INT()),
    sa.Column('ppramin_num', sa.INT()),
    sa.Column('pprasian_num', sa.INT()),
    sa.Column('pprpcisl_num', sa.INT()),
    sa.Column('pprother_num', sa.INT()),
    sa.Column('hptotal_num', sa.INT()),
    sa.Column('hphisp_num', sa.INT()),
    sa.Column('hpwhite_num', sa.INT()),
    sa.Column('hpblack_num', sa.INT()),
    sa.Column('hpamind_num', sa.INT()),
    sa.Column('hpasian_num', sa.INT()),
    sa.Column('hppcisl_num', sa.INT()),
    sa.Column('hpother_num', sa.INT()),
    sa.Column('hptsesa_num', sa.INT()),
    sa.Column('hptsesb_num', sa.INT()),
    sa.Column('hptsesc_num', sa.INT()),
    sa.Column('hptsesd_num', sa.INT()),
    sa.Column('hptsese_num', sa.INT()),
    sa.Column('hpwsesa_num', sa.INT()),
    sa.Column('hpwsesb_num', sa.INT()),
    sa.Column('hpwsesc_num', sa.INT()),
    sa.Column('hpwsesd_num', sa.INT()),
    sa.Column('hpwsese_num', sa.INT()),
    sa.Column('hpbsesa_num', sa.INT()),
    sa.Column('hpbsesb_num', sa.INT()),
    sa.Column('hpbsesc_num', sa.INT()),
    sa.Column('hpbsesd_num', sa.INT()),
    sa.Column('hpbsese_num', sa.INT()),
    sa.Column('hpasesa_num', sa.INT()),
    sa.Column('hpasesb_num', sa.INT()),
    sa.Column('hpasesc_num', sa.INT()),
    sa.Column('hpasesd_num', sa.INT()),
    sa.Column('hpasese_num', sa.INT()),
    sa.Column('hphsesa_num', sa.INT()),
    sa.Column('hphsesb_num', sa.INT()),
    sa.Column('hphsesc_num', sa.INT()),
    sa.Column('hphsesd_num', sa.INT()),
    sa.Column('hphsese_num', sa.INT()),
    sa.Column('ppdomre_val', sa.VARCHAR(50)),
    sa.Column('ipassm_t_num', sa.INT()),
    sa.Column('ipfborn_num', sa.INT()),
    sa.Column('ipassm_h_num', sa.INT()),
    sa.Column('ipassmsh_val', sa.VARCHAR(70)),
    sa.Column('ppha1_num', sa.INT()),
    sa.Column('ppha2_num', sa.INT()),
    sa.Column('ppha3_num', sa.INT()),
    sa.Column('ppha4_num', sa.INT()),
    sa.Column('ppha5_num', sa.INT()),
    sa.Column('hpha1hsesa_num', sa.INT()),
    sa.Column('hpha1hsesb_num', sa.INT()),
    sa.Column('hpha1hsesc_num', sa.INT()),
    sa.Column('hpha1hsesd_num', sa.INT()),
    sa.Column('hpha1hsese_num', sa.INT()),
    sa.Column('hpha2hsesa_num', sa.INT()),
    sa.Column('hpha2hsesb_num', sa.INT()),
    sa.Column('hpha2hsesc_num', sa.INT()),
    sa.Column('hpha2hsesd_num', sa.INT()),
    sa.Column('hpha2hsese_num', sa.INT()),
    sa.Column('hpha3hsesa_num', sa.INT()),
    sa.Column('hpha3hsesb_num', sa.INT()),
    sa.Column('hpha3hsesc_num', sa.INT()),
    sa.Column('hpha3hsesd_num', sa.INT()),
    sa.Column('hpha3hsese_num', sa.INT()),
    sa.Column('hpha4hsesa_num', sa.INT()),
    sa.Column('hpha4hsesb_num', sa.INT()),
    sa.Column('hpha4hsesc_num', sa.INT()),
    sa.Column('hpha4hsesd_num', sa.INT()),
    sa.Column('hpha4hsese_num', sa.INT()),
    sa.Column('hpha5hsesa_num', sa.INT()),
    sa.Column('hpha5hsesb_num', sa.INT()),
    sa.Column('hpha5hsesc_num', sa.INT()),
    sa.Column('hpha5hsesd_num', sa.INT()),
    sa.Column('hpha5hsese_num', sa.INT()),
    sa.Column('ppha1g0017_num', sa.INT()),
    sa.Column('ppha1g1824_num', sa.INT()),
    sa.Column('ppha1g2554_num', sa.INT()),
    sa.Column('ppha1g5564_num', sa.INT()),
    sa.Column('ppha1g65p_num', sa.INT()),
    sa.Column('ppha2g0017_num', sa.INT()),
    sa.Column('ppha2g1824_num', sa.INT()),
    sa.Column('ppha2g2554_num', sa.INT()),
    sa.Column('ppha2g5564_num', sa.INT()),
    sa.Column('ppha2g65p_num', sa.INT()),
    sa.Column('ppha3g0017_num', sa.INT()),
    sa.Column('ppha3g1824_num', sa.INT()),
    sa.Column('ppha3g2554_num', sa.INT()),
    sa.Column('ppha3g5564_num', sa.INT()),
    sa.Column('ppha3g65p_num', sa.INT()),
    sa.Column('ppha4g0017_num', sa.INT()),
    sa.Column('ppha4g1824_num', sa.INT()),
    sa.Column('ppha4g2554_num', sa.INT()),
    sa.Column('ppha4g5564_num', sa.INT()),
    sa.Column('ppha4g65p_num', sa.INT()),
    sa.Column('ppha5g0017_num', sa.INT()),
    sa.Column('ppha5g1824_num', sa.INT()),
    sa.Column('ppha5g2554_num', sa.INT()),
    sa.Column('ppha5g5564_num', sa.INT()),
    sa.Column('ppha5g65p_num', sa.INT()),
    sa.Column('ppha1mx_num', sa.INT()),
    sa.Column('ppha1pr_num', sa.INT()),
    sa.Column('ppha1do_num', sa.INT()),
    sa.Column('ppha1cu_num', sa.INT()),
    sa.Column('ppha1ca_num', sa.INT()),
    sa.Column('ppha1sa_num', sa.INT()),
    sa.Column('ppha2mx_num', sa.INT()),
    sa.Column('ppha2pr_num', sa.INT()),
    sa.Column('ppha2do_num', sa.INT()),
    sa.Column('ppha2cu_num', sa.INT()),
    sa.Column('ppha2ca_num', sa.INT()),
    sa.Column('ppha2sa_num', sa.INT()),
    sa.Column('ppha3mx_num', sa.INT()),
    sa.Column('ppha3pr_num', sa.INT()),
    sa.Column('ppha3do_num', sa.INT()),
    sa.Column('ppha3cu_num', sa.INT()),
    sa.Column('ppha3ca_num', sa.INT()),
    sa.Column('ppha3sa_num', sa.INT()),
    sa.Column('ppha4mx_num', sa.INT()),
    sa.Column('ppha4pr_num', sa.INT()),
    sa.Column('ppha4do_num', sa.INT()),
    sa.Column('ppha4cu_num', sa.INT()),
    sa.Column('ppha4ca_num', sa.INT()),
    sa.Column('ppha4sa_num', sa.INT()),
    sa.Column('ppha5mx_num', sa.INT()),
    sa.Column('ppha5pr_num', sa.INT()),
    sa.Column('ppha5do_num', sa.INT()),
    sa.Column('ppha5cu_num', sa.INT()),
    sa.Column('ppha5ca_num', sa.INT()),
    sa.Column('ppha5sa_num', sa.INT()),
    sa.Column('ipassm_a_num', sa.INT()),
    sa.Column('ipassmsa_val', sa.VARCHAR(70)),
    sa.Column('ppaa1_num', sa.INT()),
    sa.Column('ppaa2_num', sa.INT()),
    sa.Column('ppaa3_num', sa.INT()),
    sa.Column('ppaa4_num', sa.INT()),
    sa.Column('ppaa5_num', sa.INT()),
    sa.Column('hpaa1asesa_num', sa.INT()),
    sa.Column('hpaa1asesb_num', sa.INT()),
    sa.Column('hpaa1asesc_num', sa.INT()),
    sa.Column('hpaa1asesd_num', sa.INT()),
    sa.Column('hpaa1asese_num', sa.INT()),
    sa.Column('hpaa2asesa_num', sa.INT()),
    sa.Column('hpaa2asesb_num', sa.INT()),
    sa.Column('hpaa2asesc_num', sa.INT()),
    sa.Column('hpaa2asesd_num', sa.INT()),
    sa.Column('hpaa2asese_num', sa.INT()),
    sa.Column('hpaa3asesa_num', sa.INT()),
    sa.Column('hpaa3asesb_num', sa.INT()),
    sa.Column('hpaa3asesc_num', sa.INT()),
    sa.Column('hpaa3asesd_num', sa.INT()),
    sa.Column('hpaa3asese_num', sa.INT()),
    sa.Column('hpaa4asesa_num', sa.INT()),
    sa.Column('hpaa4asesb_num', sa.INT()),
    sa.Column('hpaa4asesc_num', sa.INT()),
    sa.Column('hpaa4asesd_num', sa.INT()),
    sa.Column('hpaa4asese_num', sa.INT()),
    sa.Column('hpaa5asesa_num', sa.INT()),
    sa.Column('hpaa5asesb_num', sa.INT()),
    sa.Column('hpaa5asesc_num', sa.INT()),
    sa.Column('hpaa5asesd_num', sa.INT()),
    sa.Column('hpaa5asese_num', sa.INT()),
    sa.Column('ppaa1g0017_num', sa.INT()),
    sa.Column('ppaa1g1824_num', sa.INT()),
    sa.Column('ppaa1g2554_num', sa.INT()),
    sa.Column('ppaa1g5564_num', sa.INT()),
    sa.Column('ppaa1g65p_num', sa.INT()),
    sa.Column('ppaa2g0017_num', sa.INT()),
    sa.Column('ppaa2g1824_num', sa.INT()),
    sa.Column('ppaa2g2554_num', sa.INT()),
    sa.Column('ppaa2g5564_num', sa.INT()),
    sa.Column('ppaa2g65p_num', sa.INT()),
    sa.Column('ppaa3g0017_num', sa.INT()),
    sa.Column('ppaa3g1824_num', sa.INT()),
    sa.Column('ppaa3g2554_num', sa.INT()),
    sa.Column('ppaa3g5564_num', sa.INT()),
    sa.Column('ppaa3g65p_num', sa.INT()),
    sa.Column('ppaa4g0017_num', sa.INT()),
    sa.Column('ppaa4g1824_num', sa.INT()),
    sa.Column('ppaa4g2554_num', sa.INT()),
    sa.Column('ppaa4g5564_num', sa.INT()),
    sa.Column('ppaa4g65p_num', sa.INT()),
    sa.Column('ppaa5g0017_num', sa.INT()),
    sa.Column('ppaa5g1824_num', sa.INT()),
    sa.Column('ppaa5g2554_num', sa.INT()),
    sa.Column('ppaa5g5564_num', sa.INT()),
    sa.Column('ppaa5g65p_num', sa.INT()),
    sa.Column('ppaa1jp_num', sa.INT()),
    sa.Column('ppaa1kr_num', sa.INT()),
    sa.Column('ppaa1cn_num', sa.INT()),
    sa.Column('ppaa1ph_num', sa.INT()),
    sa.Column('ppaa1in_num', sa.INT()),
    sa.Column('ppaa1vn_num', sa.INT()),
    sa.Column('ppaa1se_num', sa.INT()),
    sa.Column('ppaa1ot_num', sa.INT()),
    sa.Column('iplspanh_num', sa.INT()),
    sa.Column('pphengdm_num', sa.INT()),
    sa.Column('pphpndom_num', sa.INT()),
    sa.Column('hpilt15_num', sa.INT()),
    sa.Column('hpi1525_num', sa.INT()),
    sa.Column('hpi2535_num', sa.INT()),
    sa.Column('hpi3550_num', sa.INT()),
    sa.Column('hpi5075_num', sa.INT()),
    sa.Column('hpi75100_num', sa.INT()),
    sa.Column('hpi10015_num', sa.INT()),
    sa.Column('hpigt150_num', sa.INT()),
    sa.Column('hpiwlt15_num', sa.INT()),
    sa.Column('hpiw1525_num', sa.INT()),
    sa.Column('hpiw2535_num', sa.INT()),
    sa.Column('hpiw3550_num', sa.INT()),
    sa.Column('hpiw5075_num', sa.INT()),
    sa.Column('hpiw7510_num', sa.INT()),
    sa.Column('hpiw1001_num', sa.INT()),
    sa.Column('hpiwgt15_num', sa.INT()),
    sa.Column('hpiblt15_num', sa.INT()),
    sa.Column('hpib1525_num', sa.INT()),
    sa.Column('hpib2535_num', sa.INT()),
    sa.Column('hpib3550_num', sa.INT()),
    sa.Column('hpib5075_num', sa.INT()),
    sa.Column('hpib7510_num', sa.INT()),
    sa.Column('hpib1001_num', sa.INT()),
    sa.Column('hpibgt15_num', sa.INT()),
    sa.Column('hpialt15_num', sa.INT()),
    sa.Column('hpia1525_num', sa.INT()),
    sa.Column('hpia2535_num', sa.INT()),
    sa.Column('hpia3550_num', sa.INT()),
    sa.Column('hpia5075_num', sa.INT()),
    sa.Column('hpia7510_num', sa.INT()),
    sa.Column('hpia1001_num', sa.INT()),
    sa.Column('hpiagt15_num', sa.INT()),
    sa.Column('hpihlt15_num', sa.INT()),
    sa.Column('hpih1525_num', sa.INT()),
    sa.Column('hpih2535_num', sa.INT()),
    sa.Column('hpih3550_num', sa.INT()),
    sa.Column('hpih5075_num', sa.INT()),
    sa.Column('hpih7510_num', sa.INT()),
    sa.Column('hpih1001_num', sa.INT()),
    sa.Column('hpihgt15_num', sa.INT()),
    sa.Column('hpimed_num', sa.INT()),
    sa.Column('hpiagt_num', sa.BIGINT()),
    sa.Column('hpiagw_num', sa.BIGINT()),
    sa.Column('hpiagb_num', sa.BIGINT()),
    sa.Column('hpiaga_num', sa.BIGINT()),
    sa.Column('hpiagh_num', sa.BIGINT()),
    sa.Column('pprhwhit_num', sa.INT()),
    sa.Column('pprhblac_num', sa.INT()),
    sa.Column('pprhamin_num', sa.INT()),
    sa.Column('pprhasia_num', sa.INT()),
    sa.Column('pprhpcis_num', sa.INT()),
    sa.Column('pprhothr_num', sa.INT()),
    sa.Column('pprnhwht_num', sa.INT()),
    sa.Column('pprnhblk_num', sa.INT()),
    sa.Column('pprnhain_num', sa.INT()),
    sa.Column('pprnhasn_num', sa.INT()),
    sa.Column('pprnhpis_num', sa.INT()),
    sa.Column('pprnhotr_num', sa.INT()),
    sa.Column('hphwhite_num', sa.INT()),
    sa.Column('hphblack_num', sa.INT()),
    sa.Column('hphamind_num', sa.INT()),
    sa.Column('hphasian_num', sa.INT()),
    sa.Column('hphpcisl_num', sa.INT()),
    sa.Column('hphother_num', sa.INT()),
    sa.Column('hpnhwhit_num', sa.INT()),
    sa.Column('hpnhblac_num', sa.INT()),
    sa.Column('hpnhamin_num', sa.INT()),
    sa.Column('hpnhasia_num', sa.INT()),
    sa.Column('hpnhpcis_num', sa.INT()),
    sa.Column('hpnhothe_num', sa.INT()),
    sa.Column('ppmale_num', sa.INT()),
    sa.Column('ppfemale_num', sa.INT()),
    sa.Column('pprhispm_num', sa.INT()),
    sa.Column('pprhispf_num', sa.INT()),
    sa.Column('pprwhi_m_num', sa.INT()),
    sa.Column('pprwhi_f_num', sa.INT()),
    sa.Column('pprblk_m_num', sa.INT()),
    sa.Column('pprblk_f_num', sa.INT()),
    sa.Column('pprasn_m_num', sa.INT()),
    sa.Column('pprasn_f_num', sa.INT()),
    sa.Column('ppg0004_num', sa.INT()),
    sa.Column('ppg0509_num', sa.INT()),
    sa.Column('ppg1014_num', sa.INT()),
    sa.Column('ppg1517_num', sa.INT()),
    sa.Column('ppg1820_num', sa.INT()),
    sa.Column('ppg2124_num', sa.INT()),
    sa.Column('ppg2529_num', sa.INT()),
    sa.Column('ppg3034_num', sa.INT()),
    sa.Column('ppg3539_num', sa.INT()),
    sa.Column('ppg4044_num', sa.INT()),
    sa.Column('ppg4549_num', sa.INT()),
    sa.Column('ppg5054_num', sa.INT()),
    sa.Column('ppg5559_num', sa.INT()),
    sa.Column('ppg6064_num', sa.INT()),
    sa.Column('ppg6569_num', sa.INT()),
    sa.Column('ppg7074_num', sa.INT()),
    sa.Column('ppg7579_num', sa.INT()),
    sa.Column('ppg8084_num', sa.INT()),
    sa.Column('ppg85p_num', sa.INT()),
    sa.Column('ppgh0004_num', sa.INT()),
    sa.Column('ppgh0509_num', sa.INT()),
    sa.Column('ppgh1014_num', sa.INT()),
    sa.Column('ppgh1517_num', sa.INT()),
    sa.Column('ppgh1820_num', sa.INT()),
    sa.Column('ppgh2124_num', sa.INT()),
    sa.Column('ppgh2529_num', sa.INT()),
    sa.Column('ppgh3034_num', sa.INT()),
    sa.Column('ppgh3539_num', sa.INT()),
    sa.Column('ppgh4044_num', sa.INT()),
    sa.Column('ppgh4549_num', sa.INT()),
    sa.Column('ppgh5054_num', sa.INT()),
    sa.Column('ppgh5559_num', sa.INT()),
    sa.Column('ppgh6064_num', sa.INT()),
    sa.Column('ppgh6569_num', sa.INT()),
    sa.Column('ppgh7074_num', sa.INT()),
    sa.Column('ppgh7579_num', sa.INT()),
    sa.Column('ppgh8084_num', sa.INT()),
    sa.Column('ppgh85p_num', sa.INT()),
    sa.Column('pp_gen_z_num', sa.INT()),
    sa.Column('pp_gen_y_num', sa.INT()),
    sa.Column('pp_gen_x_num', sa.INT()),
    sa.Column('pp_gen_bb_num', sa.INT()),
    sa.Column('pp_gen_silent_num', sa.INT()),
    sa.Column('pp_gen_great_num', sa.INT()),
    sa.Column('pph_gen_z_num', sa.INT()),
    sa.Column('pph_gen_y_num', sa.INT()),
    sa.Column('pph_gen_x_num', sa.INT()),
    sa.Column('pph_gen_bb_num', sa.INT()),
    sa.Column('pph_gen_silent_num', sa.INT()),
    sa.Column('pph_gen_great_num', sa.INT()),
    sa.Column('ipsden_t_num', sa.INT()),
    sa.Column('ipsden_w_num', sa.INT()),
    sa.Column('ipsden_b_num', sa.INT()),
    sa.Column('ipsden_a_num', sa.INT()),
    sa.Column('ipsden_h_num', sa.INT()),
    sa.Column('ppah_mx_num', sa.INT()),
    sa.Column('ppah_pr_num', sa.INT()),
    sa.Column('ppah_cu_num', sa.INT()),
    sa.Column('ppah_do_num', sa.INT()),
    sa.Column('ppah_cr_num', sa.INT()),
    sa.Column('ppah_gt_num', sa.INT()),
    sa.Column('ppah_hn_num', sa.INT()),
    sa.Column('ppah_ni_num', sa.INT()),
    sa.Column('ppah_pa_num', sa.INT()),
    sa.Column('ppah_sv_num', sa.INT()),
    sa.Column('ppahcamo_num', sa.INT()),
    sa.Column('ppah_ar_num', sa.INT()),
    sa.Column('ppah_bo_num', sa.INT()),
    sa.Column('ppah_cl_num', sa.INT()),
    sa.Column('ppah_co_num', sa.INT()),
    sa.Column('ppah_ec_num', sa.INT()),
    sa.Column('ppah_py_num', sa.INT()),
    sa.Column('ppah_pe_num', sa.INT()),
    sa.Column('ppah_uy_num', sa.INT()),
    sa.Column('ppah_ve_num', sa.INT()),
    sa.Column('ppahsamo_num', sa.INT()),
    sa.Column('ppahothr_num', sa.INT()),
    sa.Column('ppl_engl_num', sa.INT()),
    sa.Column('ppl_span_num', sa.INT()),
    sa.Column('ppeltg9_num', sa.INT()),
    sa.Column('ppe912nd_num', sa.INT()),
    sa.Column('ppehisc_num', sa.INT()),
    sa.Column('ppescnd_num', sa.INT()),
    sa.Column('ppeadgr_num', sa.INT()),
    sa.Column('ppebdgr_num', sa.INT()),
    sa.Column('ppeprof_num', sa.INT()),
    sa.Column('ppedoc_num', sa.INT()),
    sa.Column('ppehlg9_num', sa.INT()),
    sa.Column('ppeh912_num', sa.INT()),
    sa.Column('ppehhsc_num', sa.INT()),
    sa.Column('ppehcnd_num', sa.INT()),
    sa.Column('ppehadg_num', sa.INT()),
    sa.Column('ppehbdg_num', sa.INT()),
    sa.Column('ppehprf_num', sa.INT()),
    sa.Column('ppocuhsp_num', sa.INT()),
    sa.Column('ppocuer_qty', sa.DECIMAL(4, 1)),
    sa.Column('hpavgsize_qty', sa.DECIMAL(4, 1)),
    sa.Column('hphavgsize_qty', sa.DECIMAL(4, 1)),
    sa.Column('ahtotal_num', sa.BIGINT()),
    sa.Column('ahfood_num', sa.BIGINT()),
    sa.Column('ahfood_home_num', sa.BIGINT()),
    sa.Column('ahfood_away_num', sa.BIGINT()),
    sa.Column('ahfhoth_nonalcbev_num', sa.BIGINT()),
    sa.Column('ahfhothnalcbev_carbonated_num', sa.BIGINT()),
    sa.Column('ahfhothnalcbev_coffee_num', sa.BIGINT()),
    sa.Column('ahfhothnalcbev_tea_num', sa.BIGINT()),
    sa.Column('ahfhothnalcbev_noncarbon_num', sa.BIGINT()),
    sa.Column('ahfhothnalcbev_bottlewater_num', sa.BIGINT()),
    sa.Column('ahfhothnalcbev_sportdrink_num', sa.BIGINT()),
    sa.Column('ahfhfrtvegprocfruit_frozen_num', sa.BIGINT()),
    sa.Column('ahfhfrtvegprocfruit_juice_num', sa.BIGINT()),
    sa.Column('ahfhfrtvegprocveg_candry_num', sa.BIGINT()),
    sa.Column('abtotal_num', sa.BIGINT()),
    sa.Column('abfood_num', sa.BIGINT()),
    sa.Column('abfood_home_num', sa.BIGINT()),
    sa.Column('abfood_away_num', sa.BIGINT()),
    sa.Column('abfhoth_nonalcbev_num', sa.BIGINT()),
    sa.Column('abfhothnalcbev_carbonated_num', sa.BIGINT()),
    sa.Column('abfhothnalcbev_coffee_num', sa.BIGINT()),
    sa.Column('abfhothnalcbev_tea_num', sa.BIGINT()),
    sa.Column('abfhothnalcbev_noncarbon_num', sa.BIGINT()),
    sa.Column('abfhothnalcbev_bottlewater_num', sa.BIGINT()),
    sa.Column('abfhothnalcbev_sportdrink_num', sa.BIGINT()),
    sa.Column('abfhfrtvegprocfruit_frozen_num', sa.BIGINT()),
    sa.Column('abfhfrtvegprocfruit_juice_num', sa.BIGINT()),
    sa.Column('abfhfrtvegprocveg_candry_num', sa.BIGINT()),
    sa.Column('attotal_num', sa.BIGINT()),
    sa.Column('atfood_num', sa.BIGINT()),
    sa.Column('atfood_home_num', sa.BIGINT()),
    sa.Column('atfood_away_num', sa.BIGINT()),
    sa.Column('atfhoth_nonalcbev_num', sa.BIGINT()),
    sa.Column('atfhothnalcbev_carbonated_num', sa.BIGINT()),
    sa.Column('atfhothnalcbev_coffee_num', sa.BIGINT()),
    sa.Column('atfhothnalcbev_tea_num', sa.BIGINT()),
    sa.Column('atfhothnalcbev_noncarbon_num', sa.BIGINT()),
    sa.Column('atfhothnalcbev_bottlewater_num', sa.BIGINT()),
    sa.Column('atfhothnalcbev_sportdrink_num', sa.BIGINT()),
    sa.Column('atfhfrtvegprocfruit_frozen_num', sa.BIGINT()),
    sa.Column('atfhfrtvegprocfruit_juice_num', sa.BIGINT()),
    sa.Column('atfhfrtvegprocveg_candry_num', sa.BIGINT()),
    sa.Column('cust_dsply_nm', sa.VARCHAR(1024)),
    sa.Column('cust_sgmnttn_trd_sgmnt_cdv', sa.VARCHAR(100)),
    sa.Column('cust_sgmnttn_trd_sgmnt_nm', sa.VARCHAR(1024)),
    sa.Column('addr_lat_lngtd_prcsn_val', sa.VARCHAR(100)),
    sa.Column('addr_lat_val', sa.DECIMAL(18, 5)),
    sa.Column('addr_lngtd_val', sa.DECIMAL(18, 5)),
    sa.Column('last_updt_dt', sf.TIMESTAMP_TZ())
)

##############################
#	mdm_msa_fl_xref
##############################
op.create_table(
    'mdm_msa_fl_xref',
    sa.Column('src_sys_rcrd_id_val', sa.BIGINT()),
    sa.Column('prty_dsply_nm', sa.VARCHAR(50)),
    sa.Column('addr_ln_1_txt', sa.VARCHAR(50)),
    sa.Column('city_nm', sa.VARCHAR(50)),
    sa.Column('terr_nm', sa.VARCHAR(50)),
    sa.Column('ctry_iso_cdv', sa.VARCHAR(50)),
    sa.Column('pstl_area_val', sa.VARCHAR(50)),
    sa.Column('prty_stts_cdv', sa.VARCHAR(50)),
    sa.Column('lat_qty', sa.DECIMAL(25, 10)),
    sa.Column('lngtd_qty', sa.DECIMAL(25, 10)),
    sa.Column('lat_lngtd_prcsn_val', sa.VARCHAR(50)),
    sa.Column('src_syd_id', sa.INT()),
    sa.Column('sap_sls_org_cd', sa.VARCHAR(50)),
    sa.Column('sap_sls_org_dsc', sa.VARCHAR(50)),
    sa.Column('sap_dstrb_chnl_cd', sa.VARCHAR(50)),
    sa.Column('sap_dstrb_chnl_dsc', sa.VARCHAR(50)),
    sa.Column('sap_dvsn_cd', sa.VARCHAR(50)),
    sa.Column('sap_dvsn_dsc', sa.VARCHAR(50)),
    sa.Column('sls_area_stts_cd', sa.VARCHAR(50)),
    sa.Column('cis_id', sa.BIGINT()),
    sa.Column('grpng_val', sa.VARCHAR(50)),
    sa.Column('last_updt_dt', sf.TIMESTAMP_TZ())
)

##############################
#	mdm_msa_pbc_xref
##############################
op.create_table(
    'mdm_msa_pbc_xref',
    sa.Column('src_sys_rcrd_id_val', sa.BIGINT()),
    sa.Column('prty_dsply_nm', sa.VARCHAR(50)),
    sa.Column('addr_ln_1_txt', sa.VARCHAR(50)),
    sa.Column('city_nm', sa.VARCHAR(50)),
    sa.Column('terr_nm', sa.VARCHAR(50)),
    sa.Column('ctry_iso_cdv', sa.VARCHAR(50)),
    sa.Column('pstl_area_val', sa.VARCHAR(50)),
    sa.Column('prty_stts_cdv', sa.VARCHAR(50)),
    sa.Column('lat_qty', sa.DECIMAL(25, 10)),
    sa.Column('lngtd_qty', sa.DECIMAL(25, 10)),
    sa.Column('lat_lngtd_prcsn_val', sa.VARCHAR(50)),
    sa.Column('grpng_val', sa.VARCHAR(50)),
    sa.Column('last_updt_dt', sf.TIMESTAMP_TZ())
)

##############################
#	btg_pep_calendar
##############################
op.create_table(
    'btg_pep_calendar',
    sa.Column('caldr_dte', sf.DATE()),
    sa.Column('caldr_day_in_wk_num', sa.SMALLINT()),
    sa.Column('caldr_day_in_wk_shrt_desc', sa.VARCHAR(3)),
    sa.Column('caldr_day_in_wk_long_desc', sa.VARCHAR(9)),
    sa.Column('caldr_day_in_mnth_num', sa.SMALLINT()),
    sa.Column('caldr_day_in_yr_num', sa.SMALLINT()),
    sa.Column('caldr_wk_start_dte', sf.DATE()),
    sa.Column('caldr_wk_end_dte', sf.DATE()),
    sa.Column('caldr_wk_in_yr_num', sa.SMALLINT()),
    sa.Column('caldr_wk_in_yr_shrt_desc', sa.VARCHAR(35)),
    sa.Column('caldr_wk_end_flg', sa.VARCHAR(1)),
    sa.Column('caldr_mnth_num', sa.SMALLINT()),
    sa.Column('caldr_mnth_shrt_desc', sa.VARCHAR(3)),
    sa.Column('caldr_mnth_long_desc', sa.VARCHAR(9)),
    sa.Column('caldr_mnth_start_dte', sf.DATE()),
    sa.Column('caldr_mnth_end_dte', sf.DATE()),
    sa.Column('caldr_mnth_end_flg', sa.VARCHAR(1)),
    sa.Column('caldr_qrtr_num', sa.SMALLINT()),
    sa.Column('caldr_qrtr_shrt_desc', sa.VARCHAR(35)),
    sa.Column('caldr_qrtr_long_desc', sa.VARCHAR(35)),
    sa.Column('caldr_qrtr_end_flg', sa.VARCHAR(1)),
    sa.Column('caldr_semi_annual_num', sa.SMALLINT()),
    sa.Column('caldr_semi_annual_desc', sa.VARCHAR(35)),
    sa.Column('caldr_yr_num', sa.SMALLINT()),
    sa.Column('caldr_yr_end_flg', sa.VARCHAR(1)),
    sa.Column('fscl_day_in_pd_num', sa.SMALLINT()),
    sa.Column('fscl_wk_start_dte', sf.DATE()),
    sa.Column('fscl_wk_end_dte', sf.DATE()),
    sa.Column('fscl_wk_in_pd_num', sa.SMALLINT()),
    sa.Column('fscl_wk_in_pd_desc', sa.VARCHAR(35)),
    sa.Column('fscl_wk_in_yr_num', sa.SMALLINT()),
    sa.Column('fscl_wk_in_yr_shrt_desc', sa.VARCHAR(35)),
    sa.Column('fscl_pd_num', sa.SMALLINT()),
    sa.Column('fscl_pd_shrt_desc', sa.VARCHAR(35)),
    sa.Column('fscl_pd_desc', sa.VARCHAR(35)),
    sa.Column('fscl_pd_end_flg', sa.VARCHAR(1)),
    sa.Column('fscl_pd_start_dte', sf.DATE()),
    sa.Column('fscl_pd_end_dte', sf.DATE()),
    sa.Column('fscl_yr_mnth_wk_num', sa.INT()),
    sa.Column('fscl_qrtr_num', sa.SMALLINT()),
    sa.Column('fscl_qrtr_shrt_desc', sa.VARCHAR(2)),
    sa.Column('fscl_qrtr_long_desc', sa.VARCHAR(35)),
    sa.Column('fscl_qrtr_end_flg', sa.VARCHAR(1)),
    sa.Column('fscl_day_in_trimester_num', sa.SMALLINT()),
    sa.Column('fscl_trimester_num', sa.SMALLINT()),
    sa.Column('fscl_trimester_shrt_desc', sa.VARCHAR(35)),
    sa.Column('fscl_trimester_desc', sa.VARCHAR(35)),
    sa.Column('fscl_trimester_end_flg', sa.VARCHAR(1)),
    sa.Column('fscl_yr_end_flg', sa.VARCHAR(1)),
    sa.Column('fscl_day_in_yr_num', sa.SMALLINT()),
    sa.Column('fscl_yr_num', sa.SMALLINT()),
    sa.Column('holiday_flg', sa.VARCHAR(1)),
    sa.Column('holiday_desc', sa.VARCHAR(35)),
    sa.Column('rpt_pd_day_num', sa.SMALLINT()),
    sa.Column('dw_srce_id', sa.INT()),
    sa.Column('dw_updt_dte', sf.DATE()),
    sa.Column('last_updt_dt', sf.TIMESTAMP_TZ())
)

##############################
#	btg_ref_calendar
##############################
op.create_table(
    'btg_ref_calendar',
    sa.Column('fl_date', sa.VARCHAR(8)),
    sa.Column('greg_dt', sf.DATE()),
    sa.Column('fl_yyyy', sa.INT()),
    sa.Column('fl_pd', sa.INT()),
    sa.Column('fl_wk', sa.INT()),
    sa.Column('fl_dd', sa.INT()),
    sa.Column('last_updt_dt', sf.TIMESTAMP_TZ())
)

##############################
#	btg_pbc_route_data
##############################
op.create_table(
    'btg_pbc_route_data',
    sa.Column('ACTV_FLG', sa.VARCHAR(2)),
    sa.Column('cur_stat_desc', sa.VARCHAR(20)),
    sa.Column('Cust_id', sa.INT()),
    sa.Column('CUST_NME', sa.VARCHAR(50)),
    sa.Column('BUS_TYPE_CTGY_CDE', sa.VARCHAR(10)),
    sa.Column('BUS_TYPE_CTGY_DESC', sa.VARCHAR(50)),
    sa.Column('bus_type_cde', sa.VARCHAR(10)),
    sa.Column('bus_type_desc', sa.VARCHAR(50)),
    sa.Column('prod_grp_cde', sa.VARCHAR(10)),
    sa.Column('PROD_GRP_DESC', sa.VARCHAR(50)),
    sa.Column('SLS_MTHD_DESC', sa.VARCHAR(50)),
    sa.Column('DELY_MTHD_DESC', sa.VARCHAR(50)),
    sa.Column('RTE_ID', sa.INT()),
    sa.Column('PROD_RTE_NUM', sa.INT()),
    sa.Column('RTE_TYPE_DESC', sa.VARCHAR(50)),
    sa.Column('RTE_PROD_GRP_DESC', sa.VARCHAR(50)),
    sa.Column('DELY_DCV_TYPE_DESC', sa.VARCHAR(50)),
    sa.Column('TERR_ID', sa.INT()),
    sa.Column('TERR_NME', sa.VARCHAR(50)),
    sa.Column('LOC_NME', sa.VARCHAR(50)),
    sa.Column('MU_NME', sa.VARCHAR(50)),
    sa.Column('BU_NME', sa.VARCHAR(50)),
    sa.Column('AV_DIVSN_NME', sa.VARCHAR(50)),
    sa.Column('AV_GM_MKT_NME', sa.VARCHAR(50)),
    sa.Column('AV_MU_NME', sa.VARCHAR(50)),
    sa.Column('loc_addr_lne_1', sa.VARCHAR(100)),
    sa.Column('city_nme', sa.VARCHAR(50)),
    sa.Column('ST_CDE', sa.VARCHAR(10)),
    sa.Column('ZIP_CDE', sa.VARCHAR(10))
)

##############################
#	btg_fl_retailer_assgnt
##############################
op.create_table(
    'btg_fl_retailer_assgnt',
    sa.Column('chain_lvl1_node_nm', sa.VARCHAR(10)),
    sa.Column('chain_lvl2_node_nm', sa.VARCHAR(10)),
    sa.Column('chain_lvl3_node_nm', sa.VARCHAR(10)),
    sa.Column('trade_chanl_descp', sa.VARCHAR(100)),
    sa.Column('fl_retailer', sa.VARCHAR(100)),
    sa.Column('last_updt_dt', sf.TIMESTAMP_TZ())
)

##############################
#	btg_pbc_retailer_assgnt
##############################
op.create_table(
    'btg_pbc_retailer_assgnt',
    sa.Column('grp1_lvl_1_desc', sa.VARCHAR(100)),
    sa.Column('grp2_lvl_1_desc', sa.VARCHAR(100)),
    sa.Column('grp2_lvl_2_desc', sa.VARCHAR(100)),
    sa.Column('bus_type_aggr_desc', sa.VARCHAR(100)),
    sa.Column('pbc_retailer', sa.VARCHAR(100)),
    sa.Column('last_updt_dt', sf.TIMESTAMP_TZ())
)

